services:
  app:
    build: ./php
    platform: linux/amd64
    volumes:
      - ./src:/var/www/src
      - ./php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql@sha256:45ad5952e4f304d39aedb02caf7e0afc30a310e66f7ab60af8acf20fd4a0f54c
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel_app
      - LANG=C.UTF-8
volumes:
  db:
